services:
  lv8girl:
    image: ghcr.io/mchappyfriskyo/lv8girl:main
    container_name: lv8girl-nnw
    ports:
      - 127.0.0.1:60009:80
    depends_on:
      - db
    volumes:
      - ./data:/var/www/html/uploads
  db:
    image: mysql:8
    container_name: lv8girl-db-nnw
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: lv8girl
      MYSQL_USER: lv8girl
      MYSQL_PASSWORD: yourpasswd
    volumes:
      - ./db:/var/lib/mysql
