services:
  lv8girl:
    image: ghcr.io/mchappyfriskyo/lv8girl:main
    container_name: lv8girl
    ports:
      - 127.0.0.1:60009:80
    depends_on:
      - db
    volumes:
      - ./data:/var/www/html/uploads
    restart: no
  db:
    image: mysql:5.7.26
    container_name: lv8girl-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: lv8girl
      MYSQL_USER: lv8girl
      MYSQL_PASSWORD: yourpasswd
    volumes:
      - ./db:/var/lib/mysql
    command:
      - --bind-address=0.0.0.0
    ports: []
networks: {}
